# Generated by Django 4.0.6 on 2022-07-20 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_furniture_product_furniture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cololr',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='thumnail_image_url',
            new_name='thumbnail_image_url',
        ),
    ]
