# Generated by Django 4.0.6 on 2022-07-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='name',
            new_name='english_name',
        ),
        migrations.AddField(
            model_name='color',
            name='korean_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='korean_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=45)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_image', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
    ]
